// SPDX-License-Identifier: Apache-2.0
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const root = fileURLToPath(new URL("../../../", import.meta.url));
const cli = join(root, "apps/cli/dist/index.js");
const example = (name: string) => join(root, "examples", `${name}.yaml`);
const out = mkdtempSync(join(tmpdir(), "ccg-cli-"));

interface Run {
  status: number;
  stdout: string;
  stderr: string;
}

function ccg(...args: string[]): Run {
  try {
    const stdout = execFileSync("node", [cli, ...args], { encoding: "utf8", stdio: "pipe" });
    return { status: 0, stdout, stderr: "" };
  } catch (error) {
    const e = error as { status: number; stdout: string; stderr: string };
    return { status: e.status, stdout: e.stdout ?? "", stderr: e.stderr ?? "" };
  }
}

describe("exit codes", () => {
  it("0 when a spec is clean", () => {
    expect(ccg("lint", example("diamond")).status).toBe(0);
  });

  it("1 when the linter finds errors", () => {
    expect(ccg("lint", example("linear-chain")).status).toBe(1);
  });

  it("0 when there are only warnings", () => {
    expect(ccg("lint", example("self-grading")).status).toBe(0);
  });

  it("2 on bad usage", () => {
    expect(ccg("lint").status).toBe(2);
    expect(ccg("nonsense").status).toBe(2);
  });

  it("2 on an unreadable spec, without a stack trace", () => {
    const run = ccg("lint", join(out, "missing.yaml"));
    expect(run.status).toBe(2);
    expect(run.stderr).not.toContain("at ");
  });
});

/**
 * Node's parseArgs rejects `--no-x` unless `allowNegative` is set, so every
 * negatable flag the usage text advertises needs a test — they were all
 * silently broken before this.
 */
describe("negatable flags actually parse", () => {
  it("render --no-header", () => {
    const run = ccg("render", example("diamond"), "--no-header");
    expect(run.status).toBe(0);
    expect(run.stdout).not.toContain(">diamond<");
  });

  it("render --no-embed-font", () => {
    const run = ccg("render", example("diamond"), "--no-embed-font");
    expect(run.status).toBe(0);
    expect(run.stdout).not.toContain("@font-face");
    expect(run.stdout).not.toContain("SIL Open Font");
  });

  it("render --no-grain", () => {
    const run = ccg("render", example("diamond"), "--no-grain");
    expect(run.status).toBe(0);
    expect(run.stdout).not.toContain("feTurbulence");
  });

  it("codegen --no-banner", () => {
    const run = ccg("codegen", example("diamond"), "--no-banner");
    expect(run.status).toBe(0);
    expect(run.stdout).not.toContain("Generated by ccgrapher");
  });

  it("lint --no-color", () => {
    const run = ccg("lint", example("diamond"), "--no-color");
    expect(run.status).toBe(0);
    // eslint-disable-next-line no-control-regex
    expect(run.stdout).not.toMatch(/\[/);
  });
});

describe("render", () => {
  it("picks the format from the output extension", () => {
    for (const [ext, marker] of [
      ["svg", "<svg xmlns="],
      ["mmd", "flowchart TD"],
      ["excalidraw", '"type": "excalidraw"'],
    ] as const) {
      const file = join(out, `diamond.${ext}`);
      expect(ccg("render", example("diamond"), "-o", file).status).toBe(0);
      expect(readFileSync(file, "utf8")).toContain(marker);
    }
  });

  it("--fix renders the repaired graph", () => {
    const before = join(out, "before.svg");
    const after = join(out, "after.svg");
    ccg("render", example("linear-chain"), "-o", before);
    ccg("render", example("linear-chain"), "--fix", "-o", after);

    const width = (f: string) => Number(/width="(\d+)"/.exec(readFileSync(f, "utf8"))![1]);
    // The whole point: repairing turns a tall chain into a wide graph.
    expect(width(after)).toBeGreaterThan(width(before) * 1.5);
  });

  it("rejects an unknown format", () => {
    expect(ccg("render", example("diamond"), "-f", "pdf").status).toBe(2);
  });
});

describe("the round trip survives the CLI", () => {
  it("codegen then ingest reproduces the spec", () => {
    const ts = join(out, "diamond.ts");
    ccg("codegen", example("diamond"), "-t", "plain-ts", "-o", ts);

    const run = ccg("ingest", ts);
    expect(run.status).toBe(0);
    expect(run.stderr).toBe("");
    expect(run.stdout).toContain("name: diamond");
    expect(run.stdout).toContain("id: worker_1");
    expect(run.stdout).toContain("source: url");
  });

  it("ingest --lint audits the code rather than the spec", () => {
    const ts = join(out, "chain.ts");
    ccg("codegen", example("linear-chain"), "-t", "plain-ts", "-o", ts);

    const run = ccg("ingest", ts, "--lint");
    expect(run.status).toBe(1);
    expect(run.stdout).toContain("Critical path: 6 layers -> 4 layers");
  });
});

describe("help", () => {
  it("lists every command", () => {
    const run = ccg("--help");
    expect(run.status).toBe(0);
    for (const command of ["lint", "render", "codegen", "ingest"]) {
      expect(run.stdout).toContain(`ccg ${command}`);
    }
  });
});
