// SPDX-License-Identifier: Apache-2.0
import type { Graph, NodeSpec } from "@ccgrapher/core";

export const TARGETS = ["claude-code", "plain-ts", "langgraph"] as const;
export type Target = (typeof TARGETS)[number];

export interface EmitOptions {
  /** Header comment naming the spec this was generated from. On by default. */
  readonly banner?: boolean;
  /** Source path to name in the banner. */
  readonly specPath?: string;
}

export interface Emitter {
  readonly target: Target;
  readonly extension: string;
  emit(graph: Graph, options: EmitOptions): string;
}

/** A rank's worth of nodes: everything here can run at once. */
export interface Stage {
  readonly rank: number;
  readonly nodes: readonly NodeSpec[];
}

/** Valid JS identifier for a node id, so `review-a` becomes `review_a`. */
export function identifier(id: string): string {
  const cleaned = id.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
}

export function banner(graph: Graph, options: EmitOptions, target: Target): string[] {
  if (options.banner === false) return [];
  return [
    `// Generated by ccgrapher from ${options.specPath ?? `${graph.spec.name}.yaml`} — target: ${target}.`,
    "// The graph and the runtime cannot drift: regenerate rather than editing here.",
    `// Spec: ${graph.spec.name}`,
    ...(graph.spec.goal ? [`// Goal: ${graph.spec.goal}`] : []),
    "",
  ];
}

export const quote = (text: string) => JSON.stringify(text);
