// SPDX-License-Identifier: Apache-2.0
import type { BoundarySpec, Graph, NodeSpec, StoreSpec } from "@ccgrapher/core";

/** Targets that emit one file. `codegen()` returns it as a string. */
export const TARGETS = ["claude-code", "plain-ts", "langgraph"] as const;
export type Target = (typeof TARGETS)[number];

/** Targets that emit a directory. `codegenFiles()` returns it as a set of files. */
export const DIRECTORY_TARGETS = ["managed-agents"] as const;
export type DirectoryTarget = (typeof DIRECTORY_TARGETS)[number];

export const ALL_TARGETS = [...TARGETS, ...DIRECTORY_TARGETS] as const;
export type AnyTarget = Target | DirectoryTarget;

/**
 * Generated files, keyed by a relative POSIX path. Paths are plain (no `..`, no
 * leading `/`) and the keys come back sorted, so two runs over one spec produce
 * the same set in the same order.
 */
export type Files = Readonly<Record<string, string>>;

export interface EmitOptions {
  /** Header comment naming the spec this was generated from. On by default. */
  readonly banner?: boolean;
  /** Source path to name in the banner. */
  readonly specPath?: string;
}

export interface Emitter {
  readonly target: Target;
  readonly extension: string;
  emit(graph: Graph, options: EmitOptions): string;
  /** What this target cannot honour about this graph, in plain words. */
  warnings?(graph: Graph): string[];
}

/**
 * The second form of the contract, for a target whose output is a directory
 * rather than one file. Everything else about it is the same: deterministic,
 * banner on by default, and warnings on the side rather than in the output.
 */
export interface DirectoryEmitter {
  readonly target: DirectoryTarget;
  emitFiles(graph: Graph, options: EmitOptions): Files;
  /** What this target cannot honour about this graph, in plain words. */
  warnings?(graph: Graph): string[];
}

/** A rank's worth of nodes: everything here can run at once. */
export interface Stage {
  readonly rank: number;
  readonly nodes: readonly NodeSpec[];
}

/** Valid JS identifier for a node id, so `review-a` becomes `review_a`. */
export function identifier(id: string): string {
  const cleaned = id.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
}

export function banner(graph: Graph, options: EmitOptions, target: AnyTarget): string[] {
  if (options.banner === false) return [];
  return [
    `// Generated by ccgrapher from ${options.specPath ?? `${graph.spec.name}.yaml`} — target: ${target}.`,
    "// The graph and the runtime cannot drift: regenerate rather than editing here.",
    `// Spec: ${graph.spec.name}`,
    ...(graph.spec.goal ? [`// Goal: ${graph.spec.goal}`] : []),
    ...(graph.spec.schedule ? [`// Schedule: ${graph.spec.schedule}`] : []),
    ...Object.entries(graph.spec.stores ?? {}).map(([id, store]) => storeLine(id, store)),
    ...(graph.spec.boundaries ?? []).map(boundaryLine),
    "",
  ];
}

/**
 * `// Store: ledger owner=agent records=post:brief-channel`. Ids hold no
 * whitespace, so spaces separate the parts. `ingest` reads this line back, so
 * the format is a contract with it.
 */
export function storeLine(id: string, store: StoreSpec): string {
  return `// Store: ${id} owner=${store.owner}${store.records ? ` records=${store.records}` : ""}`;
}

/**
 * For the targets `ingest` cannot read back. The schedule and the stores still
 * appear in the banner, as comments, and effects and guards appear nowhere, so
 * nothing in the generated code checks an effect or keeps a store's owner.
 */
export function crossRunWarnings(graph: Graph, target: AnyTarget): string[] {
  const spec = graph.spec;
  const out: string[] = [];
  if (spec.schedule !== undefined) {
    out.push(`the schedule survives only as a banner comment in the ${target} target: nothing in the generated code runs it, and ingest cannot read it back.`);
  }
  const stores = Object.keys(spec.stores ?? {});
  if (stores.length > 0) {
    out.push(
      `${stores.length === 1 ? "store" : "stores"} ${stores.map((s) => `'${s}'`).join(", ")} ${stores.length === 1 ? "survives" : "survive"} only as banner comments in the ${target} target: ingest cannot read them back, and nothing in the generated code keeps an owner or an order.`,
    );
  }
  for (const node of spec.nodes) {
    const claims = [
      ...(node.effects?.length ? [`effects ${node.effects.join(" ")}`] : []),
      ...(node.guards?.length ? [`guards ${node.guards.join(" ")}`] : []),
    ];
    if (claims.length > 0) {
      out.push(`'${node.id}' declares ${claims.join(" and ")}, which the ${target} target does not carry.`);
    }
  }
  return out;
}

/**
 * `// Boundary: gather (read-only): research dedupe vote — gather and check`.
 * The id and members are space-free, so spaces can separate them; the label
 * goes last because it is the one part that may contain anything. `ingest`
 * reads this line back, so the format is a contract with it.
 */
export function boundaryLine(boundary: BoundarySpec): string {
  const access = boundary.access ? ` (${boundary.access})` : "";
  const label = boundary.label ? ` — ${boundary.label}` : "";
  return `// Boundary: ${boundary.id}${access}: ${boundary.members.join(" ")}${label}`;
}

/**
 * For the targets `ingest` cannot read back. The boundary still appears in the
 * banner, as a comment, but nothing in the generated code holds a member to it.
 */
export function boundaryWarnings(graph: Graph, target: AnyTarget): string[] {
  return (graph.spec.boundaries ?? []).map(
    (boundary) =>
      `boundary '${boundary.id}' survives only as a banner comment in the ${target} target: ingest cannot read it back${boundary.access === "read-only" ? ", and nothing in the generated code keeps its members read-only" : ""}.`,
  );
}

export const quote = (text: string) => JSON.stringify(text);
