// SPDX-License-Identifier: Apache-2.0
import { fileURLToPath } from "node:url";
import { withEdges } from "@ccgrapher/core";
import { loadGraph } from "@ccgrapher/core/node";
import { lint } from "@ccgrapher/lint";
import ts from "typescript";
import { describe, expect, it } from "vitest";
import { codegen, jsonSchemaFor, objectSchema, stages, TARGETS, tsType } from "../src/index.js";

const examples = fileURLToPath(new URL("../../../examples/", import.meta.url));
const fixture = (name: string) => loadGraph(`${examples}${name}.yaml`);

const ALL = [
  "diamond",
  "research-desk",
  "route-auth-audit",
  "linear-chain",
  "self-grading",
  "wide-fanin",
] as const;

const AsyncFunction = Object.getPrototypeOf(async function () {
  /* probe */
}).constructor as new (...args: string[]) => unknown;

/** Parses the emitted workflow the way the runtime would: async body, top-level return. */
function parseWorkflow(code: string): void {
  const body = code.replace(/^export /gm, "");
  new AsyncFunction("agent", "parallel", "pipeline", "phase", "log", "args", "budget", body);
}

/** Real TypeScript diagnostics, not just a transpile. */
function typecheck(code: string, fileName = "generated.ts"): ts.Diagnostic[] {
  const options: ts.CompilerOptions = {
    strict: true,
    noEmit: true,
    target: ts.ScriptTarget.ES2022,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    module: ts.ModuleKind.ESNext,
    skipLibCheck: true,
  };
  const source = ts.createSourceFile(fileName, code, ts.ScriptTarget.ES2022, true);
  const host = ts.createCompilerHost(options);
  const original = host.getSourceFile.bind(host);
  host.getSourceFile = (name, ...rest) =>
    name === fileName ? source : original(name, ...rest);

  const program = ts.createProgram([fileName], options, host);
  return [
    ...program.getSyntacticDiagnostics(source),
    ...program.getSemanticDiagnostics(source),
  ].filter(
    // The langgraph target imports a package we deliberately do not depend on.
    (d) => d.code !== 2307,
  );
}

const format = (diagnostics: ts.Diagnostic[]) =>
  diagnostics
    .map((d) => `${d.code}: ${ts.flattenDiagnosticMessageText(d.messageText, " ")}`)
    .join("\n");

describe("every target emits parseable code for every fixture", () => {
  it.each(ALL)("claude-code / %s parses as a workflow script", (name) => {
    expect(() => parseWorkflow(codegen(fixture(name), "claude-code"))).not.toThrow();
  });

  it.each(ALL)("plain-ts / %s typechecks under strict", (name) => {
    const diagnostics = typecheck(codegen(fixture(name), "plain-ts"));
    expect(format(diagnostics)).toBe("");
  });

  it.each(ALL)("langgraph / %s has no syntax errors", (name) => {
    const code = codegen(fixture(name), "langgraph");
    const source = ts.createSourceFile("g.ts", code, ts.ScriptTarget.ES2022, true);
    // @ts-expect-error -- parseDiagnostics is internal but is the only way to
    // get syntax errors without resolving @langchain/langgraph.
    expect(source.parseDiagnostics ?? []).toHaveLength(0);
  });

  it.each(TARGETS)("%s emits a banner naming the source spec", (target) => {
    expect(codegen(fixture("diamond"), target, { specPath: "examples/diamond.yaml" })).toContain(
      "examples/diamond.yaml",
    );
    expect(codegen(fixture("diamond"), target, { banner: false })).not.toContain("Generated by");
  });
});

describe("claude-code — the structure matches the graph", () => {
  const code = codegen(fixture("diamond"), "claude-code");

  it("runs the five workers in one parallel() and nothing else", () => {
    expect([...code.matchAll(/await parallel\(/g)]).toHaveLength(1);
    expect(code).toContain(
      "const [worker_1, worker_2, worker_3, worker_4, worker_5] = await parallel([",
    );
  });

  it("awaits split, then the workers, then checker, then merge", () => {
    const order = ["split the job", "worker 1", "checker", "merge into one answer"];
    const positions = order.map((label) => code.indexOf(label));
    expect(positions).toEqual([...positions].sort((a, b) => a - b));
    expect(positions.every((p) => p >= 0)).toBe(true);
  });

  it("declares one phase per rank", () => {
    expect([...code.matchAll(/^phase\(/gm)]).toHaveLength(stages(fixture("diamond")).length);
  });

  it("guards the fan-in on what arrived, not on its own output", () => {
    expect(code).toContain(
      "const checkerInputs = [worker_1, worker_2, worker_3, worker_4, worker_5].filter(Boolean)",
    );
    expect(code).toContain("if (checkerInputs.length !== 5)");
    expect(code).not.toContain("checker.length");
  });

  it("notes fresh context as a comment, never inside the options object", () => {
    expect(code).toContain("// checker runs in a fresh context");
    expect(code).not.toMatch(/\{[^\n}]*\/\/[^\n]*\}/);
  });

  it("maps model tiers", () => {
    expect(code).toContain('model: "haiku"');
    expect(code).toContain('model: "opus"');
  });
});

describe("claude-code — fanOut and worktree", () => {
  const code = codegen(fixture("route-auth-audit"), "claude-code");

  it("maps fanOut to a capped parallel map, not twenty literal nodes", () => {
    expect(code).toContain("const auditItems = toList(discover).slice(0, 20)");
    expect(code).toContain("auditItems.map((item, i) => () =>");
    expect(code).not.toContain("audit_1");
  });

  it("maps worktree to isolation", () => {
    expect(code).toContain('isolation: "worktree"');
  });

  it("defines toList only when something fans out", () => {
    expect(code).toContain("const toList =");
    expect(codegen(fixture("diamond"), "claude-code")).not.toContain("const toList =");
  });

  it("guards the fan-in against the cap", () => {
    expect(code).toContain("if (audit.length !== 20)");
  });
});

describe("plain-ts", () => {
  const code = codegen(fixture("diamond"), "plain-ts");

  it("types every node's input and output", () => {
    expect(code).toContain("export interface SplitIn {");
    expect(code).toContain("export interface WorkerNumber1Out {".replace("Number1", "1"));
    expect(code).toContain("  angle: string;");
    expect(code).toContain('  verdict: "keep" | "drop";');
  });

  it("uses Promise.all for a rank with several nodes", () => {
    expect(code).toContain("await Promise.all([");
  });

  it("renders array descriptors as arrays", () => {
    expect(codegen(fixture("linear-chain"), "plain-ts")).toContain("issues_a: string[];");
  });
});

describe("langgraph", () => {
  const code = codegen(fixture("diamond"), "langgraph");

  it("wires start, every spec edge, and end", () => {
    expect(code).toContain('.addEdge(START, "split")');
    for (const edge of fixture("diamond").spec.edges) {
      expect(code).toContain(`.addEdge("${edge.from}", "${edge.to}")`);
    }
    expect(code).toContain('.addEdge("merge", END)');
  });

  it("accumulates a channel several nodes write at once", () => {
    // claim is produced by five workers concurrently.
    expect(code).toMatch(/claim: Annotation<string\[\]>\(\{ reducer:/);
  });

  it("carries the fan-in guards through as notes", () => {
    expect(code).toContain("checker: expects 5");
  });
});

describe("--fix generates from the repaired graph", () => {
  it("drops the wasted waits", () => {
    const original = fixture("linear-chain");
    const repaired = withEdges(original, lint(original).repairedEdges);

    const before = codegen(original, "plain-ts");
    const after = codegen(repaired, "plain-ts");

    // As written the three reviewers are a staircase of separate awaits; once
    // repaired they collapse into one Promise.all.
    expect(before).not.toContain("await Promise.all([");
    expect(after).toContain(
      "const [review_aResult, review_bResult, lint_docsResult] = await Promise.all([",
    );
  });
});

describe("field descriptors", () => {
  it("maps the vocabulary the specs actually use", () => {
    expect(jsonSchemaFor("string")).toEqual({ type: "string" });
    expect(jsonSchemaFor("url")).toEqual({ type: "string", description: "url" });
    expect(jsonSchemaFor("boolean")).toEqual({ type: "boolean" });
    expect(jsonSchemaFor("string[]")).toEqual({ type: "array", items: { type: "string" } });
    expect(jsonSchemaFor("keep|drop")).toEqual({ type: "string", enum: ["keep", "drop"] });
    expect(jsonSchemaFor("YYYY-MM-DD")).toEqual({ type: "string", description: "YYYY-MM-DD" });
  });

  it("produces a closed object schema", () => {
    expect(objectSchema({ a: "string", b: "number" })).toEqual({
      type: "object",
      properties: { a: { type: "string" }, b: { type: "number" } },
      required: ["a", "b"],
      additionalProperties: false,
    });
  });

  it("maps to TypeScript too", () => {
    expect(tsType("string[]")).toBe("string[]");
    expect(tsType("keep|drop")).toBe('"keep" | "drop"');
    expect(tsType("object")).toBe("Record<string, unknown>");
  });
});
