// SPDX-License-Identifier: Apache-2.0
import { readdirSync } from "node:fs";
import { posix } from "node:path";
import { fileURLToPath } from "node:url";
import { buildGraph, SpecError, type Graph, type NodeSpec, type WorkflowSpec } from "@ccgrapher/core";
import { loadGraph } from "@ccgrapher/core/node";
import { describe, expect, it } from "vitest";
import YAML from "yaml";
import {
  codegen,
  codegenFiles,
  codegenWarnings,
  isAnyTarget,
  isDirectoryTarget,
  isTarget,
  MODEL_ID,
  TARGETS,
  type Files,
  type Target,
} from "../src/index.js";

const examples = fileURLToPath(new URL("../../../examples/", import.meta.url));
const EXAMPLES = readdirSync(examples)
  .filter((f) => f.endsWith(".yaml"))
  .map((f) => f.slice(0, -".yaml".length))
  .sort();
const fixture = (name: string) => loadGraph(`${examples}${name}.yaml`);
const emit = (graph: Graph, banner = true) =>
  codegenFiles(graph, "managed-agents", { banner, specPath: "spec.yaml" });

// --- the static validator ----------------------------------------------------
//
// Every rule below is a documented Managed Agents field list or limit (the
// agent configuration fields, the agent toolset's eight tools, the MCP and
// skill reference shapes, the multiagent roster rules, the environment's
// networking block, and `ant apply`'s directory conventions). Nothing here is
// taken from the emitter, so the emitter cannot pass by agreeing with itself.

const AGENT_FIELDS = new Set(["name", "model", "system", "tools", "mcp_servers", "skills", "description", "multiagent", "metadata"]);
const TOOLSET = new Set(["bash", "read", "write", "edit", "glob", "grep", "web_fetch", "web_search"]);
const POLICIES = new Set(["always_allow", "always_ask", "auto"]);
/** The current models in the docs' model list (Glasswing-only ones left out). */
const MODELS = new Set([
  "claude-fable-5-1",
  "claude-fable-5",
  "claude-opus-5-5",
  "claude-opus-5",
  "claude-opus-4-8",
  "claude-opus-4-7",
  "claude-opus-4-6",
  "claude-sonnet-5-5",
  "claude-sonnet-5",
  "claude-sonnet-4-6",
  "claude-haiku-5-5",
  "claude-haiku-4-5",
]);
const ENV_FIELDS = new Set(["name", "description", "config", "metadata"]);
const NETWORKING_FIELDS = new Set(["type", "allowed_hosts", "allow_package_managers", "allow_mcp_servers"]);
const KEBAB = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const PLAIN = /^[A-Za-z0-9_][A-Za-z0-9._-]*$/;

type Doc = Record<string, any>;

function frontmatter(text: string): { fm: Doc; body: string } | undefined {
  const m = text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  return m ? { fm: YAML.parse(m[1]!) as Doc, body: m[2]! } : undefined;
}

function validate(files: Files): string[] {
  const problems: string[] = [];
  const names = new Set<string>();
  let anyMcp = false;

  for (const path of Object.keys(files)) {
    for (const part of path.split("/")) if (!PLAIN.test(part)) problems.push(`${path}: '${part}' is not a plain name`);
  }

  const agentFiles = Object.keys(files).filter((p) => /^agents\/[^/]+\/agent\.md$/.test(p));
  for (const path of agentFiles) {
    const folder = path.split("/")[1]!;
    if (!KEBAB.test(folder)) problems.push(`${path}: folder is not kebab-case`);
    const parsed = frontmatter(files[path]!);
    if (!parsed) {
      problems.push(`${path}: no frontmatter`);
      continue;
    }
    const { fm, body } = parsed;
    for (const key of Object.keys(fm)) if (!AGENT_FIELDS.has(key)) problems.push(`${path}: unknown agent field ${key}`);
    if (typeof fm.name !== "string" || fm.name.length < 1 || fm.name.length > 256) problems.push(`${path}: name missing or over 256`);
    if (fm.name === "self") problems.push(`${path}: name 'self' is reserved`);
    if (names.has(fm.name)) problems.push(`${path}: duplicate name ${fm.name}`);
    names.add(fm.name);
    if (!MODELS.has(fm.model)) problems.push(`${path}: model ${fm.model} is not in the docs' model list`);
    if (fm.description !== undefined && (typeof fm.description !== "string" || fm.description.length > 2048)) {
      problems.push(`${path}: description over 2048`);
    }
    if (body.length > 100_000) problems.push(`${path}: system prompt over 100K`);
    if (/Generated by|ccgrapher from|regenerate rather than editing|^\s*(?:\/\/|#\s*Spec:)/im.test(body)) {
      problems.push(`${path}: banner text in the system prompt`);
    }

    const md = fm.metadata ?? {};
    if (Object.keys(md).length > 16) problems.push(`${path}: metadata over 16 pairs`);
    for (const [k, v] of Object.entries(md)) {
      if (k.length > 64) problems.push(`${path}: metadata key ${k} over 64`);
      if (typeof v !== "string" || v.length > 512) problems.push(`${path}: metadata ${k} not a string of at most 512`);
    }

    const servers = new Set<string>();
    for (const server of fm.mcp_servers ?? []) {
      anyMcp = true;
      for (const k of Object.keys(server)) if (!["type", "name", "url"].includes(k)) problems.push(`${path}: unknown mcp_servers field ${k}`);
      if (server.type !== "url" || !server.name || !server.url) problems.push(`${path}: mcp server malformed`);
      if (servers.has(server.name)) problems.push(`${path}: duplicate mcp server ${server.name}`);
      servers.add(server.name);
    }
    if (servers.size > 20) problems.push(`${path}: over 20 mcp servers`);

    const tools: Doc[] = fm.tools ?? [];
    if (tools.length > 128) problems.push(`${path}: over 128 tools`);
    const policy = (p: Doc | undefined) => {
      if (p !== undefined && !POLICIES.has(p.type)) problems.push(`${path}: unknown permission policy ${p.type}`);
    };
    for (const tool of tools) {
      if (tool.type === "agent_toolset_20260401") {
        policy(tool.default_config?.permission_policy);
        for (const c of tool.configs ?? []) {
          if (!TOOLSET.has(c.name)) problems.push(`${path}: unknown toolset tool ${c.name}`);
          policy(c.permission_policy);
        }
      } else if (tool.type === "mcp_toolset") {
        if (!servers.has(tool.mcp_server_name)) problems.push(`${path}: toolset for undeclared server ${tool.mcp_server_name}`);
        policy(tool.default_config?.permission_policy);
        for (const c of tool.configs ?? []) {
          for (const k of Object.keys(c)) if (!["name", "enabled", "permission_policy"].includes(k)) problems.push(`${path}: mcp config field ${k}`);
          policy(c.permission_policy);
        }
      } else if (tool.type === "custom") {
        if (!tool.name || tool.input_schema?.type !== "object") problems.push(`${path}: custom tool malformed`);
      } else {
        problems.push(`${path}: unknown tool type ${tool.type}`);
      }
    }

    const skills: Doc[] = fm.skills ?? [];
    if (skills.length > 20) problems.push(`${path}: over 20 skills`);
    for (const s of skills) {
      if (!["anthropic", "custom"].includes(s.type) || typeof s.skill_id !== "string") problems.push(`${path}: skill malformed`);
    }

    if (fm.multiagent) {
      const ma = fm.multiagent;
      if (ma.type !== "coordinator") problems.push(`${path}: multiagent.type must be coordinator`);
      if (!Array.isArray(ma.agents) || ma.agents.length < 1 || ma.agents.length > 20) problems.push(`${path}: roster must hold 1 to 20`);
      for (const ref of ma.agents ?? []) {
        if (typeof ref !== "string") continue;
        const target = posix.normalize(posix.join(posix.dirname(path), ref));
        const rostered = files[target] && frontmatter(files[target]!);
        if (!rostered) problems.push(`${path}: roster path ${ref} does not exist`);
        else if (rostered.fm.multiagent) problems.push(`${path}: roster member ${ref} has its own roster`);
      }
    }
  }

  const environments = Object.keys(files).filter((p) => /^agents\/[^/]+\/environment\.yaml$/.test(p));
  if (environments.length !== 1) problems.push(`expected one environment, found ${environments.length}`);
  for (const path of environments) {
    const env = YAML.parse(files[path]!) as Doc;
    for (const k of Object.keys(env)) if (!ENV_FIELDS.has(k)) problems.push(`${path}: unknown environment field ${k}`);
    if (env.config?.type !== "cloud") problems.push(`${path}: config.type is not cloud`);
    if (env.config?.networking?.type !== "limited") problems.push(`${path}: networking is not limited`);
    for (const k of Object.keys(env.config?.networking ?? {})) {
      if (!NETWORKING_FIELDS.has(k)) problems.push(`${path}: unknown networking field ${k}`);
    }
    if (Boolean(env.config?.networking?.allow_mcp_servers) !== anyMcp) problems.push(`${path}: allow_mcp_servers does not match the agents`);
  }

  // A README with frontmatter would look like a resource to a walk.
  if (files["README.md"]?.startsWith("---")) problems.push("README.md has frontmatter");
  return problems;
}

const isAgentNode = (node: NodeSpec) => node.kind !== "gate" && node.model !== null;

// --- tests -------------------------------------------------------------------

describe("managed-agents — research-desk", () => {
  const files = emit(fixture("research-desk"));

  it("writes one agent per model node, the environment, and a README", () => {
    expect(Object.keys(files)).toEqual([
      "README.md",
      "agents/plan/agent.md",
      "agents/report/agent.md",
      "agents/research-desk/environment.yaml",
      "agents/research/agent.md",
      "agents/skeptic-correct/agent.md",
      "agents/skeptic-current/agent.md",
      "agents/skeptic-source/agent.md",
    ]);
  });

  it("names each agent by node id, in a kebab-case folder", () => {
    expect(frontmatter(files["agents/skeptic-correct/agent.md"]!)!.fm.name).toBe("skeptic_correct");
  });

  it("resolves tiers to full model ids", () => {
    expect(frontmatter(files["agents/research/agent.md"]!)!.fm.model).toBe("claude-haiku-5-5");
    expect(frontmatter(files["agents/plan/agent.md"]!)!.fm.model).toBe("claude-opus-5-5");
  });

  it("emits no coordinator, and no agent for plain code or the gate", () => {
    for (const path of Object.keys(files)) {
      expect(path).not.toMatch(/agents\/(dedupe|vote|gate)\//);
      const parsed = path.endsWith("agent.md") ? frontmatter(files[path]!) : undefined;
      expect(parsed?.fm.multiagent).toBeUndefined();
    }
    expect(files["README.md"]).toContain("- `dedupe` (reduce): plain code, no model");
    expect(files["README.md"]).toContain("- `gate` (gate): a person approves");
  });

  it("puts the banner in the frontmatter as comments, never in the body", () => {
    const text = files["agents/plan/agent.md"]!;
    const [fm, body] = text.split("\n---\n");
    expect(fm).toContain("# Generated by ccgrapher from spec.yaml — target: managed-agents.");
    expect(fm).toContain("# Boundary: gather (read-only):");
    expect(body).not.toContain("Generated by");
  });

  it("records the spec in metadata", () => {
    const md = frontmatter(files["agents/research/agent.md"]!)!.fm.metadata;
    expect(md).toEqual({
      ccg_boundary: "gather (read-only)",
      ccg_fanout_cap: "5",
      ccg_fanout_over: "angle",
      ccg_kind: "worker",
      ccg_node: "research",
      ccg_spec: "research-desk",
      ccg_tier: "cheap",
    });
  });

  it("says a fresh-context verifier is one, in its prompt", () => {
    expect(frontmatter(files["agents/skeptic-source/agent.md"]!)!.body).toContain("You are a verifier with a fresh context.");
  });

  it("grants the write tool only to a node that declares writes, and the web to nobody", () => {
    const enabled = (path: string) =>
      (frontmatter(files[path]!)!.fm.tools[0].configs as Doc[]).filter((c) => c.enabled).map((c) => c.name);
    expect(enabled("agents/report/agent.md")).toEqual(["write"]);
    expect(enabled("agents/research/agent.md")).toEqual([]);
  });

  it("uses limited networking with nothing opted in", () => {
    expect(YAML.parse(files["agents/research-desk/environment.yaml"]!)).toEqual({
      config: { networking: { type: "limited" }, type: "cloud" },
      name: "research-desk",
    });
  });

  it("tells the reader to apply by naming files", () => {
    expect(files["README.md"]).toContain("ant apply --dry-run agents/plan/agent.md");
    expect(files["README.md"]).not.toMatch(/ant apply( --dry-run)? \.\s*$/m);
  });
});

describe("managed-agents — the static validator passes on every example", () => {
  it.each(EXAMPLES)("%s", (name) => {
    const graph = fixture(name);
    const files = emit(graph);
    expect(validate(files)).toEqual([]);

    const expected = graph.spec.nodes.filter(isAgentNode).map((n) => n.id).sort();
    const named = Object.keys(files)
      .filter((p) => p.endsWith("/agent.md"))
      .map((p) => frontmatter(files[p]!)!.fm.name as string)
      .sort();
    expect(named).toEqual(expected);
  });

  it.each(EXAMPLES)("%s without a banner carries no banner anywhere", (name) => {
    const files = emit(fixture(name), false);
    expect(validate(files)).toEqual([]);
    for (const [path, text] of Object.entries(files)) {
      expect(text).not.toContain("Generated by");
      if (path.endsWith(".md") && path !== "README.md") expect(text.split("\n---\n")[0]).not.toMatch(/^# /m);
    }
  });

  it("checks the validator against a file that breaks the rules", () => {
    const files = emit(fixture("research-desk"));
    const broken = {
      ...files,
      "agents/plan/agent.md": files["agents/plan/agent.md"]!
        .replace('model: "claude-opus-5-5"', 'model: "claude-opus-9"\nsystem_prompt: "x"')
        .replace("Your job:", "Generated by hand. Your job:"),
    };
    expect(validate(broken)).toEqual([
      "agents/plan/agent.md: unknown agent field system_prompt",
      "agents/plan/agent.md: model claude-opus-9 is not in the docs' model list",
      "agents/plan/agent.md: banner text in the system prompt",
    ]);
  });

  it("knows the shared tier table's ids", () => {
    for (const id of Object.values(MODEL_ID)) expect(MODELS.has(id)).toBe(true);
  });
});

describe("managed-agents — deterministic", () => {
  it.each(EXAMPLES)("%s is byte-identical across runs, paths sorted", (name) => {
    const a = emit(fixture(name));
    const b = emit(fixture(name));
    expect(JSON.stringify(a)).toBe(JSON.stringify(b));
    expect(Object.keys(a)).toEqual([...Object.keys(a)].sort());
  });

  it("writes every mapping's keys in sorted order", () => {
    const text = emit(fixture("research-desk"))["agents/report/agent.md"]!;
    const top = text
      .split("\n---\n")[0]!
      .split("\n")
      .filter((line) => /^[a-z_]+:/.test(line))
      .map((line) => line.split(":")[0]);
    expect(top).toEqual(["description", "metadata", "model", "name", "tools"]);
  });
});

const spec = (nodes: Array<Partial<NodeSpec> & { id: string }>, extra: Partial<WorkflowSpec> = {}): Graph =>
  buildGraph({
    version: 1,
    name: "capabilities",
    edges: [],
    ...extra,
    nodes: nodes.map((n) => ({ label: n.id, kind: "worker", in: {}, out: {}, ...n }) as NodeSpec),
  });

describe("managed-agents — uses: and its warnings", () => {
  const graph = spec([
    { id: "lead", model: "strong", uses: ["agent:helper", "agent:outside", "mcp:docs/search", "mcp:docs/fetch", "mcp:wiki"] },
    { id: "helper", model: "cheap", uses: ["skill:xlsx", "skill:house-style", "plugin:formatter", "thing:else"] },
    { id: "loose" },
  ]);
  const files = emit(graph);
  const warnings = codegenWarnings(graph, "managed-agents");
  const lead = frontmatter(files["agents/lead/agent.md"]!)!.fm;
  const helper = frontmatter(files["agents/helper/agent.md"]!)!.fm;

  it("still passes the validator", () => {
    expect(validate(files)).toEqual([]);
  });

  it("maps mcp: to a server with a placeholder URL and an allowlisted toolset", () => {
    expect(lead.mcp_servers).toEqual([
      { name: "docs", type: "url", url: "YOUR_MCP_URL_DOCS" },
      { name: "wiki", type: "url", url: "YOUR_MCP_URL_WIKI" },
    ]);
    expect(lead.tools[1]).toEqual({
      configs: [
        { enabled: true, name: "fetch", permission_policy: { type: "always_ask" } },
        { enabled: true, name: "search", permission_policy: { type: "always_ask" } },
      ],
      default_config: { enabled: false },
      mcp_server_name: "docs",
      type: "mcp_toolset",
    });
    expect(lead.tools[2]).toEqual({
      default_config: { permission_policy: { type: "always_ask" } },
      mcp_server_name: "wiki",
      type: "mcp_toolset",
    });
    expect(YAML.parse(files["agents/capabilities/environment.yaml"]!).config.networking.allow_mcp_servers).toBe(true);
    expect(warnings).toContain(
      "'lead' uses the MCP server 'docs', and the spec names no URL for it: agents/lead/agent.md carries the placeholder YOUR_MCP_URL_DOCS, and its tools are set to always_ask, which pauses an unattended run on every call until it is confirmed.",
    );
  });

  it("maps agent: to a roster entry, a sibling by path and anything else by placeholder", () => {
    expect(lead.multiagent).toEqual({
      agents: ["../helper/agent.md", { id: "YOUR_AGENT_ID_OUTSIDE", type: "agent" }],
      type: "coordinator",
    });
    expect(warnings.some((w) => w.includes("YOUR_AGENT_ID_OUTSIDE"))).toBe(true);
  });

  it("maps skill: to a prebuilt skill by name, and a custom one by placeholder", () => {
    expect(helper.skills).toEqual([
      { skill_id: "YOUR_SKILL_ID_HOUSE_STYLE", type: "custom" },
      { skill_id: "xlsx", type: "anthropic" },
    ]);
    expect(warnings.some((w) => w.includes("YOUR_SKILL_ID_HOUSE_STYLE"))).toBe(true);
  });

  it("warns that a plugin has no equivalent, and keeps the claim in metadata", () => {
    expect(warnings).toContain(
      "'helper' uses plugin:formatter, and Managed Agents has no equivalent of a plugin: the agent is generated without it, and the claim survives only in its metadata.",
    );
    expect(warnings).toContain(
      "'helper' uses thing:else, which the managed-agents target has no mapping for: the claim survives only in its metadata.",
    );
    expect(helper.metadata.ccg_uses).toBe("skill:xlsx skill:house-style plugin:formatter thing:else");
  });

  it("gives a node with no tier the strong model, and says so once", () => {
    expect(frontmatter(files["agents/loose/agent.md"]!)!.fm.model).toBe("claude-opus-5-5");
    expect(frontmatter(files["agents/loose/agent.md"]!)!.fm.metadata.ccg_tier).toBe("unset");
    expect(warnings.filter((w) => w.includes("no model tier"))).toEqual([
      "'loose' declares no model tier, so the managed-agents target gives it the strong tier (claude-opus-5-5).",
    ]);
  });

  it("names every placeholder it writes in a warning", () => {
    const placeholders = new Set(Object.values(files).flatMap((text) => text.match(/YOUR_[A-Z0-9_]+/g) ?? []));
    for (const p of placeholders) expect(warnings.some((w) => w.includes(p))).toBe(true);
  });

  it("warns nothing for research-desk, whose boundary has no MCP tool to leak through", () => {
    expect(codegenWarnings(fixture("research-desk"), "managed-agents")).toEqual([]);
  });

  it("keeps metadata values inside 512 characters", () => {
    const long = spec([{ id: "w", model: "cheap", writes: Array.from({ length: 60 }, (_, i) => `out/file-${i}.md`) }]);
    const md = frontmatter(emit(long)["agents/w/agent.md"]!)!.fm.metadata;
    expect(md.ccg_writes.length).toBe(512);
    expect(validate(emit(long))).toEqual([]);
  });
});

describe("managed-agents — names it refuses", () => {
  it("refuses two nodes that would share a folder", () => {
    const graph = spec([{ id: "review-a", model: "cheap" }, { id: "review_a", model: "cheap" }]);
    expect(() => emit(graph)).toThrow(SpecError);
    expect(() => emit(graph)).toThrow("would share the agent folder agents/review-a/");
  });

  it("refuses a node named self", () => {
    expect(() => emit(spec([{ id: "self", model: "cheap" }]))).toThrow("reserved");
  });
});

describe("the target list", () => {
  it("keeps TARGETS to the targets that emit one file", () => {
    expect([...TARGETS]).toEqual(["claude-code", "plain-ts", "langgraph"]);
    expect(isTarget("managed-agents")).toBe(false);
    expect(isDirectoryTarget("managed-agents")).toBe(true);
    expect(isAnyTarget("managed-agents")).toBe(true);
  });

  it("points codegen() at codegenFiles() for a directory target", () => {
    expect(() => codegen(fixture("diamond"), "managed-agents" as Target)).toThrow("call codegenFiles() instead");
  });

  it("renders the claude-code tiers from the shared table as aliases", () => {
    const code = codegen(fixture("research-desk"), "claude-code");
    expect(code).toContain('model: "haiku"');
    expect(code).toContain('model: "opus"');
    expect(code).not.toContain("claude-opus-5-5");
  });
});
